version: "3.5"
services:
  bh_testapp:
   image: registry.zanox.com/bh-testapp:latest
   tty: true
   ports:
    - "80:80"
   deploy: 
    replicas: 2
   healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost"]
    interval: 1m
    timeout: 10s
    retries: 3
    start_period: 40s
